### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by Benjamin-Dobell** [tjakubo2/TTS_lib#2]
Thanks for sharing these libraries, they look great. However, as it stands no-one other than yourself can legally use these scripts, unless you explicitly grant us a license to do so, or explicitly contribute the scripts to the public domain.

If you could please add a `LICENSE` file to this repository that'd be very much appreciated? Preferably MIT, but really that's up to you 😄

**Comment by tjakubo** [comment]
Hey, thanks for reminding, I'll add license file later today when I'm on a desktop. It's MIT for all this and submodules ofc :)
