### ISSUE TITLE
[ObjType] Where is Vector

### ISSUE THREAD

**Issue by Zehir** [tjakubo2/TTS_lib#3]
Hello, the ObjType script need Vector but where can I find it ?

**Comment by tjakubo** [comment]
Vector was removed during a cleanup some time ago since it was really shitty - forgot to purge it from other libs too, sorry!

**Comment by tjakubo** [comment]
ObjType should work fine now, no Vector needed, it was very scarcely used anyway. And if you are missing a Vector type, it is coming to TTS in the future as a built in type :)

**Comment by Zehir** [comment]
Where you find this info ?

**Comment by tjakubo** [comment]
If you mean a built in Vector type, it was hinted by the devs some time ago on forums or Discord. No idea when though.

**Comment by Zehir** [comment]
Is this vector script you talking about ?
https://github.com/eruber/TTS_ULib/blob/master/TTS_ULib/vectors.ttslua

**Comment by tjakubo** [comment]
No, I'm not really sure what you're asking about now though :P
My packages used my implementation of Vector, which was half-assed and eventually removed. For now I have no plans on remaking it so I just removed this dependency from ObjType as it was simple enough.
