### ISSUE TITLE
EventSub not saving data on onSave

### ISSUE THREAD

**Issue by Zehir** [tjakubo2/TTS_lib#4]
Hi,

About the EventSub, can I use it to save data ?
Ex:
```Lua
EventSub.Register('onSave', function ()
    print("onSave register")
    return JSON.encode({
        savedSomething = "yellow"
    })
end)
```
Dont put "yellow" in LuaScriptState but print "onSave register"
But This : 
```Lua
function onSave()
    debug("onSave function")
    return JSON.encode({
        savedSomething = "blue"
    })
end
```
Put "blue" in LuaScriptState and print "onSave function"

And as expected with both only "onSave function" is printed

Thanks

**Comment by Zehir** [comment]
You do the same in SaveManager so I guess that a tts problem

**Comment by tjakubo** [comment]
EventSub is there to allow multiple handlers for events, so it doesn't mesh well with ``onSave`` - you can't really determine which handler should have its return value passed over to the event.

Like you mentioned, SaveManager is a fit for that case, made to work specifically with TTS onSave/onLoad events and their arg/return quirks.
